### ISSUE TITLE
Icon color Change

### ISSUE THREAD

**Issue by vijayvargiyakhushboo** [optimistanoop/jhora#9]
@optimistanoop , In the case when the transaction table appearing in red color so,the delete icon is not appearing proper because its color also pure red.So can we change the delete icon color as black color.

**Comment by optimistanoop** [comment]
Thanks, Really nice catch for this issue. We wll fix asap.

**Comment by optimistanoop** [comment]
@vijayvargiyakhushboo 👍

**Comment by mahesh-maxx** [comment]
Hi, project manager of jhora here, developers are not fast in fixing bugs here (busy in doing features) hence I have to fix issues. 
I have fixed the issue by using light pink color (favorite of girls).
btw nice Vikram.

**Comment by vijayvargiyakhushboo** [comment]
@mahesh-maxx , I am confusing here you told you are project manager but @optimistanoop  told me i am project manager.I think you are QA, Anoop is a developer and me project manager 💃 .
@optimistanoop - right ?

**Comment by optimistanoop** [comment]
@vijayvargiyakhushboo @mahesh-maxx heheheheh
